/*
  # Safety Agent Tables

  1. New Tables
    - `risk_assessments`: Store risk assessments generated by the Safety Agent
    - `site_conditions`: Store site-specific conditions and restrictions
    - `tasks`: Store scheduled tasks and their requirements
    - `task_equipment`: Store equipment associated with tasks
*/

-- Create risk_assessments table
CREATE TABLE IF NOT EXISTS risk_assessments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  site_id UUID NOT NULL,
  assessment JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ
);

-- Create site_conditions table
CREATE TABLE IF NOT EXISTS site_conditions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  site_id UUID NOT NULL,
  conditions JSONB NOT NULL,
  restrictions TEXT[],
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ
);

-- Create tasks table
CREATE TABLE IF NOT EXISTS tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  site_id UUID NOT NULL,
  type TEXT NOT NULL,
  description TEXT NOT NULL,
  scheduled_start TIMESTAMPTZ NOT NULL,
  scheduled_end TIMESTAMPTZ NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('pending', 'in-progress', 'completed', 'cancelled')),
  assigned_to UUID[],
  hazards TEXT[],
  safety_requirements TEXT[],
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ
);

-- Create task_equipment table
CREATE TABLE IF NOT EXISTS task_equipment (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  task_id UUID REFERENCES tasks(id) ON DELETE CASCADE,
  equipment_type TEXT NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1,
  requirements TEXT[],
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- Enable Row Level Security
ALTER TABLE risk_assessments ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_conditions ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_equipment ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Users can view risk assessments"
  ON risk_assessments
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Users can view site conditions"
  ON site_conditions
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Users can view tasks"
  ON tasks
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Users can view task equipment"
  ON task_equipment
  FOR SELECT
  TO authenticated
  USING (true);